In [5]:
from config import parameters
import jax
import jax.numpy as np
# Generate a sequence of random numbers
sequence_length = 10  # Adjust the length as needed
random_numbers = jax.random.uniform(parameters['key'], shape=(sequence_length,))
idx = 0
newPos = [0,0]

actions = list(['n','s','e','w'])
choices = jax.random.choice(parameters['key'], np.array((0,1,2,3)),(np.shape(actions)[0],4))

In [147]:
X = 10
Y = 5
states=[]
for i in range(X+1):
    for j in range(Y+1):
        states.append(i+j*(X+1))        

print(np.unique(np.array(states)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65]


In [153]:
import numpy as np

# Define the shape of the 3D matrix [I, J, K]
I, J, K = 2, 2, 3

# Create a meshgrid of indices for each dimension
i, j, k = np.meshgrid(np.arange(I), np.arange(J), np.arange(K))#, indexing='ij')

# Stack the indices to create unique identifiers
unique_identifiers = np.stack((i, j, k), axis=-1)

# Now, 'unique_identifiers' is a NumPy array with unique identifiers for each element in the 3D matrix


In [1]:
from config import rl

rl['nStates']

4096

In [2]:
import numpy as np

# Create a 3x3 array (you can use your own array)
array_3x3 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# Convert the 3x3 array into a list of 9 values
flattened_list = [element for row in array_3x3 for element in row]

# Print the flattened list
print(flattened_list)


[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
row, col = 1, 2  # Example index (row, col) for the 3x3 matrix

# Calculate the index in the flattened list
index_in_list = row * 3 + col

# Access the element in the flattened list
element = flattened_list[index_in_list]

print(f"Element at index ({row}, {col}) in the 3x3 matrix: {element}")


Element at index (1, 2) in the 3x3 matrix: 6


In [10]:
def index_to_element(matrix_shape, index):
    """
    Converts an index for a matrix of any shape and dimensionality
    into the corresponding element in the flattened list.

    Args:
    - matrix_shape (tuple): The shape of the matrix as a tuple (rows, columns, depth, ...).
    - index (tuple): The index for the matrix as a tuple (row, column, depth, ...).

    Returns:
    - element: The corresponding element in the flattened list.
    """
    if len(matrix_shape) != len(index):
        raise ValueError("Matrix shape and index must have the same dimensionality.")

    if not all(0 <= i < dim for i, dim in zip(index, matrix_shape)):
        raise ValueError("Index is out of bounds for the given matrix shape.")

    flattened_index = 0
    multiplier = 1

    for i in range(len(matrix_shape) - 1, -1, -1):
        flattened_index += index[i] * multiplier
        multiplier *= matrix_shape[i]

    return flattened_index

# Example usage:
matrix_shape = (3, 3)  # Example matrix shape (3x3)
index = (2, 2)         # Example index for the matrix

element = index_to_element(matrix_shape, index)
print(f"Element at index {index} in the matrix: {element}")


Element at index (2, 2) in the matrix: 8


In [27]:
print(index_to_element((2,5),(1,3)))

8


In [29]:
1 - True

0

In [32]:
# 1 = 1
# 0 = -1

for i in range(2):
    print(2*i-1)

-1
1


In [44]:
array_3x3[np.arange(3),1] += np.arange(5,8)

In [46]:
sa_pairs = np.array([(s,a) for s in range(rl['nStates']) for a in range(rl['nActions'])])

In [47]:
print(np.shape(sa_pairs))

(16384, 2)


In [49]:
print(rl['nStates'],rl['nActions'])

4096 4


In [51]:
valid = np.ones(rl['nStates'] * rl['nActions']) * False

In [52]:
np.shape(valid)

(16384,)

In [80]:
arr1 = np.ones((1,4))*0
arr2 = np.ones((1,4))*1
arr3 = np.ones((1,4))*2

In [81]:
arr4 = np.array((arr1,arr2,arr3))

In [82]:
arr4

array([[[0., 0., 0., 0.]],

       [[1., 1., 1., 1.]],

       [[2., 2., 2., 2.]]])

In [89]:
np.sum(arr4,axis=0)

array([[3., 3., 3., 3.]])

In [109]:
import jax
import jax.numpy as jnp
from jax import jit, random

# Define your function that relies on a random key
def my_function(rng_key):
    # Generate random numbers using the rng_key
    random_numbers = random.normal(rng_key, (5,))
    # Perform some computation using the random numbers
    # result = jnp.sum(random_numbers)
    
    return random_numbers

# Set a fixed random seed for reproducibility
seed = 42
rng_key = random.PRNGKey(seed)
jit_my_function = jit(my_function)

for i in range(5):
    rng_key,subkey = random.split(rng_key)
    result = jit_my_function(subkey)
    print(result)



# JIT-compile the function


# Call the JIT-compiled function with the fixed rng_key


[-0.55338794  0.944283   -0.74176395 -0.5769758   1.1251862 ]
[-0.32761317 -0.4066346   1.2469071   1.1900425   1.100263  ]
[ 0.52089006  0.5769043  -0.843142   -0.88776976 -0.26607993]
[ 1.4053283  -1.656194   -0.80294687  0.63603115  0.0813799 ]
[-1.3662882   0.2240449  -0.07971714  0.6435944  -0.65730476]


In [110]:
environment = {
    "actions":{'n': np.array([0, -1]), 
               's': np.array([0, 1]), 
               'w': np.array([-1, 0]), 
               'e': np.array([1, 0])}}


In [114]:
gDirIdx = list(environment['actions'].values())

In [129]:
np.where(np.all(np.array(list(environment['actions'].values()))==[0,1],axis=1))
# gDirIdx.index([0,-1])

(array([1]),)

In [134]:
np.argwhere([0,0,0,])

array([], shape=(0, 1), dtype=int64)

In [136]:
test1= np.array([0,-1])
test2= np.array([0,0])

np.array_equal(test1,test2)

False

In [137]:
# 2.22
100 * (60*2 + 22)

14200

In [138]:
14200/60

236.66666666666666

In [139]:
236/60

3.933333333333333

In [143]:
input_array = np.array([0,1])

print(tuple(input_array))

(0, 1)


In [33]:
import jax.numpy as np
from config import environment

x = 4
y = 4
if (all(np.greater_equal(np.array([environment['size']['X'],environment['size']['Y']]),np.array([x,y]))) and 
    all(np.greater_equal(np.array([x,y]),np.array([0,0])))) and not np.any(np.all(environment['obstacles'] == newPos, axis=1)):
    print('true')
else:
    print('false')

true
